# Generated by Django 3.2.18 on 2023-05-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_alter_activation_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='family_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.familytree'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpermissionrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usergrouprole')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userrole')),
            ],
        ),
        migrations.AlterField(
            model_name='activation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
